---
title: "Data wrangling"
author: "AEM"
date: "October 22, 2018"
output: html_document
---

```{r}
library(tidyverse) # install.packages("tidyverse")
```

## imported code, read data
```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')


#inspect data set
gapminder # preview of data
head(gapminder, 10) # preview of first x rows
tail(gapminder, 4) #preview of bottom x rows

summary(gapminder) # gives min/max/quart/med summary of data
#install.packages("skimr")
library(skimr)

skim(gapminder) # more info

names(gapminder) # gives header names

dim(gapminder) # dimensions

ncol(gapminder) # number of columns

nrow(gapminder) # number of rows

```

# dplyr
```{r}
# filter by rows
filter(gapminder, lifeExp <29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Peru")) # how to look at multiple countries
filter(gapminder, country == "Mexico", year == 2002)

#determining mean life exp for sweden
swe <- filter(gapminder, country == "Sweden")
lifswe <- swe$lifeExp ## how to call one column of data
mean(lifswe)

#select by column
select(gapminder, year, lifeExp) # select(data, column1, column2, ect)
select(gapminder, -continent, -year) #how to remove columns

# select and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)


```

## Pipe operator %>% (and then)
```{r}
gapminder %>% head() #start with data, then %<% then command, the same as head(gapminder)

#same as cambodia above, but with pipes
gap_cambodia <- gapminder %>% filter(country == "Cambodia")
gap_cambodia2 <- gap_cambodia %>% select(-continent, -lifeExp)

# okay now we add pipes, makes  it cleaner
gap_cambodia <- gapminder %>% 
  filter(country == "Cambodia") %>% 
  select(-continent, -lifeExp)

# Shortcut!! --> %>% (ctrl+shift+M)


```

## mutate
```{r}
#mutate adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder)) ## adds new column, called index, numbered 1 to n 

gapminder %>% mutate(planet = "Earth") ## adds planet column

# math
gapminder %>% mutate(gdp = pop * gdpPercap) ## new column of gdp

## challenge
gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop*gdpPercap) %>% 
  mutate(max_gdp =max(gdp))



```


